apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: loki-ingress
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`loki.blaze64.xyz`)
      services:
        - name: loki
          port: 3100
