apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-ingress
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`grafana.blaze64.xyz`)
      services:
        - name: grafana
          port: 80
