apiVersion: v1
kind: Service
metadata:
  name: traefik-web-service

spec:
  type: LoadBalancer
  loadBalancerIP: 34.82.231.50
  ports:
    - targetPort: 80
      port: 80
  selector:
    app: traefik

---
apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard-service

spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: traefik
