service:
  enabled: true
  type: LoadBalancer
  spec:
    loadBalancerIP: 34.82.231.50

ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.blaze64.xyz`)
    entryPoints: ["web"]
    middlewares:
      - name: traefik-dashboard-auth

extraObjects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: traefik-dashboard-auth-secret
    type: kubernetes.io/basic-auth
    stringData:
      username: admin
      password: traefik

  - apiVersion: traefik.io/v1alpha1
    kind: Middleware
    metadata:
      name: traefik-dashboard-auth
    spec:
      basicAuth:
        secret: traefik-dashboard-auth-secret
