apiVersion: apps/v1
kind: Deployment
metadata:
  name: mission-ctrl-deployment
  labels:
    app: mission-ctrl
spec:
  replicas: 4
  selector:
    matchLabels:
      app: mission-ctrl
  template:
    metadata:
      labels:
        app: mission-ctrl
    spec:
      initContainers:
        - name: mission-ctrl-migrate
          image: ghcr.io/blazeisclone/spaceops-mission-ctrl:v0.0.6
          command:
            - make
            - migrate
          env:
            - name: PORT
              value: "3000"
            - name: BASE_PATH
              value: /api/v1
            - name: MYSQL_HOST
              value: $(MYSQL_HOST)
            - name: MYSQL_PORT
              value: $(MYSQL_PORT)
            - name: MYSQL_USER
              value: $(MYSQL_USER)
            - name: MYSQL_DATABASE
              value: $(MYSQL_DATABASE)
            - name: MYSQL_PASSWORD
              value: $(MYSQL_PASSWORD)

      containers:
        - name: mission-ctrl-app
          image: ghcr.io/blazeisclone/spaceops-mission-ctrl:v0.0.6
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          env:
            - name: PORT
              value: "3000"
            - name: BASE_PATH
              value: /api/v1
            - name: MYSQL_HOST
              value: $(MYSQL_HOST)
            - name: MYSQL_PORT
              value: $(MYSQL_PORT)
            - name: MYSQL_USER
              value: $(MYSQL_USER)
            - name: MYSQL_DATABASE
              value: $(MYSQL_DATABASE)
            - name: MYSQL_PASSWORD
              value: $(MYSQL_PASSWORD)
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "150m"
