apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mission-ctrl
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  source:
    path: apps/mission-ctrl/envs/prod
    repoURL: https://github.com/BlazeIsClone/spaceops-cloud-config.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated: null
    syncOptions:
      - PruneLast=true
