apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingress.yml

namespace: prod

configMapGenerator:
  - name: mission-ctrl-configmap
    literals:
      - PORT="3000"
      - BASE_PATH=/api/v1
      - MYSQL_HOST=35.203.176.250
      - MYSQL_PORT="3306"

secretGenerator:
  - name: mission-ctrl-secret
    literals:
      - MYSQL_USER=spaceops
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=spaceops_mission_ctrl

replicas:
  - name: mission-ctrl-deployment
    count: 4
